INSERT INTO SECURITY_PERMISSION VALUES (200,'SEED',NOW(),0,NULL,NULL,0,'Permission for Library Admin','ROLE_LIBADMIN');

INSERT INTO SECURITY_PERMISSION VALUES (300,'SEED',NOW(),0,NULL,NULL,0,'Permission for Library Member','ROLE_LIBMEMBER');

INSERT INTO SECURITY_PERMISSION VALUES (400,'SEED',NOW(),0,NULL,NULL,0,'Permission for Data Operator','ROLE_DATAOPERATOR');

INSERT INTO SECURITY_PERMISSION VALUES (500,'SEED',NOW(),0,NULL,NULL,0,'Permission for User','ROLE_USER');

INSERT INTO SECURITY_GROUP VALUES(200,'SEED',NOW(),0,NULL,NULL,0,'LIBADMIN','1');

INSERT INTO SECURITY_GROUP VALUES(300,'SEED',NOW(),0,NULL,NULL,0,'LIBMEMBER','2');

INSERT INTO SECURITY_GROUP VALUES(400,'SEED',NOW(),0,NULL,NULL,0,'DATAOPERATOR','3');

INSERT INTO SECURITY_GROUP VALUES(500,'SEED',NOW(),0,NULL,NULL,0,'USER','4');

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (200,200);

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (300,300);

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (400,400);

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (500,500);

INSERT INTO USER_LOGIN VALUES (200,'SEED',NOW(),1,NULL,NULL,0,'la','la',1,'libraryPanel','1');

INSERT INTO USER_LOGIN VALUES (300,'SEED',NOW(),1,NULL,NULL,0,'member','member',1,'viewDemography','1');

INSERT INTO USER_LOGIN VALUES (400,'SEED',NOW(),1,NULL,NULL,0,'dataop','dataop',1,'registerPatient','1');

INSERT INTO USER_LOGIN VALUES (500,'SEED',NOW(),1,NULL,NULL,0,'test','test',1,'viewDemography','1');

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (200,200);

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (300,300);

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (400,400);

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (500,500);

insert into HOME_PAGE_DETAILS values (200,'SEED',NOW(),1,NULL,NULL,0,'Library Management Administrator Home Page','libraryPanel');

insert into HOME_PAGE_DETAILS values (300,'SEED',NOW(),1,NULL,NULL,0,'Library Management Member Home Page','bookListForMember');

insert into HOME_PAGE_DETAILS values (400,'SEED',NOW(),1,NULL,NULL,0,'Data Operator Home Page','dataOperatorHome');

insert into HOME_PAGE_DETAILS values (500,'SEED',NOW(),1,NULL,NULL,0,'USER Home Page','UserrHome');

ALTER TABLE MEMBER ADD UNIQUE (MEMBER_ID);

ALTER TABLE BOOK ADD UNIQUE (ISBN);